/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./../src/components/Layout/Header/Breadcrumb.vue')['default']
    Button: typeof import('./../src/components/Base/Button/index.vue')['default']
    Cascader: typeof import('./../src/components/TablePro/FormItems/Cascader.vue')['default']
    Checkbox: typeof import('./../src/components/TablePro/FormItems/Checkbox.vue')['default']
    CopyBtn: typeof import('./../src/components/Base/CopyBtn/index.vue')['default']
    DatePicker: typeof import('./../src/components/TablePro/FormItems/DatePicker.vue')['default']
    DateRange: typeof import('./../src/components/TablePro/FormItems/DateRange.vue')['default']
    Dialog: typeof import('./../src/components/Base/Dialog/index.vue')['default']
    Drawer: typeof import('./../src/components/Base/Drawer/index.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Header: typeof import('./../src/components/Layout/Header/index.vue')['default']
    InputNumber: typeof import('./../src/components/TablePro/FormItems/InputNumber.vue')['default']
    Layout: typeof import('./../src/components/Layout/index.vue')['default']
    Main: typeof import('./../src/components/Layout/Main/index.vue')['default']
    MenuList: typeof import('./../src/components/Layout/Sidebar/MenuList.vue')['default']
    ModuleTitle: typeof import('./../src/components/Base/ModuleTitle/index.vue')['default']
    NavbarAction: typeof import('./../src/components/Layout/Header/NavbarAction.vue')['default']
    NumberRange: typeof import('./../src/components/TablePro/FormItems/NumberRange.vue')['default']
    Radio: typeof import('./../src/components/TablePro/FormItems/Radio.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./../src/components/TablePro/FormItems/Select.vue')['default']
    SelectText: typeof import('./../src/components/TablePro/FormItems/SelectText.vue')['default']
    Sidebar: typeof import('./../src/components/Layout/Sidebar/index.vue')['default']
    TablePro: typeof import('./../src/components/TablePro/index.vue')['default']
    TagsView: typeof import('./../src/components/Layout/TagsView/index.vue')['default']
    Text: typeof import('./../src/components/TablePro/FormItems/Text.vue')['default']
    UploadFile: typeof import('./../src/components/UploadFile/index.vue')['default']
    VideoPlayer: typeof import('./../src/components/Base/VideoPlayer/index.vue')['default']
  }
}
